version: "3"

services:
    app:
        build: .
        command: npm start
        ports:
            - "3000:3000"
        volumes: 
            - .:/usr/app
        networks: 
            - server 


    redis:
        image: redis:alpine
        command: redis-server
        ports:
            - "3032:6379"
        networks: 
            - server     

            
    mongo:
        image: mongo
        command: --serviceExecutor adaptive
        ports:
            - "27017:27017"
        networks: 
            - server    
            

networks: 
    server:
        driver: bridge 